import {
  Company,
  Person,
  CompanyExperience,
  ComplianceEvidence,
  Project,
  ConflictAlert,
} from "@/types/procurement";

export const MOCK_COMPANIES: Company[] = [
  {
    id: "aos",
    legalName: "CV ALFA OMEGA SOLUSINDO",
    businessType: "CV",
    address: "Jl. Pemuda No. 142, Kel. Sekyu, Semarang",
    city: "Semarang",
    phone: "(024) 8415-9920",
    email: "info@alfaomegasolusindo.co.id",
    website: "https://alfaomegasolusindo.co.id",
    bankName: "Bank Jateng Cabang Utama Semarang",
    bankAccountNumber: "1-003-99281-2",
    bankAccountHolder: "CV ALFA OMEGA SOLUSINDO",
    directors: [
      {
        id: "dir-1",
        fullName: "Ir. Agus Wahyudi, M.T.",
        position: "Direktur",
        idCardNumber: "3374011205800003",
        taxIdNumber: "72.449.102.4-503.000",
        effectiveFrom: "2018-03-15",
        isSignatory: true,
        deedReference: "Akta No. 12 Notaris Hendra, S.H.",
      },
    ],
    legalDocuments: [
      {
        id: "leg-aos-1",
        documentType: "NIB",
        documentNumber: "9120003921822",
        issueDate: "2019-06-10",
        issuingAuthority: "OSS Republik Indonesia",
        sourceFile: "NIB_CV_Alfa_Omega_Solusindo.pdf",
        verificationState: "CONFIRMED",
      },
      {
        id: "leg-aos-2",
        documentType: "SBU",
        documentNumber: "SBU-IT-2024-9982",
        issueDate: "2024-01-15",
        validUntil: "2027-01-14",
        issuingAuthority: "LPJK / Kemenkominfo",
        sourceFile: "SBU_AOS_2024.pdf",
        verificationState: "CONFIRMED",
      },
    ],
    taxRecord: {
      id: "tax-aos",
      npwpNumber: "72.449.102.4-503.000",
      kppName: "KPP Pratama Semarang Barat",
      registeredDate: "2018-04-01",
      status: "AKTIF",
    },
    branding: {
      numberingPattern: "001/SP-AOS/{ROMAN}/{YEAR}",
      footerText: "CV ALFA OMEGA SOLUSINDO • Solutions & Digital Innovation",
    },
  },
  {
    id: "ezra",
    legalName: "PT EZRA PRATAMA",
    businessType: "PT",
    address: "Kawasan Industri Wijayakusuma Blok C-12, Semarang",
    city: "Semarang",
    phone: "(024) 7620-883",
    email: "corporate@ezrapratama.co.id",
    website: "https://ezrapratama.co.id",
    bankName: "Bank Mandiri Cabang Pandanaran",
    bankAccountNumber: "135-00-1928374-1",
    bankAccountHolder: "PT EZRA PRATAMA",
    directors: [
      {
        id: "dir-ezra-1",
        fullName: "Dr. Pratama Ezra Wijaya, S.T., M.M.",
        position: "Direktur Utama",
        idCardNumber: "3374082210750001",
        taxIdNumber: "02.192.483.1-504.000",
        effectiveFrom: "2015-08-10",
        isSignatory: true,
        deedReference: "Akta Notaris Siti Rahmah S.H. No. 45",
      },
    ],
    legalDocuments: [
      {
        id: "leg-ezra-1",
        documentType: "NIB",
        documentNumber: "8120001928374",
        issueDate: "2018-11-20",
        issuingAuthority: "OSS Kemeninves",
        sourceFile: "NIB_PT_Ezra_Pratama.pdf",
        verificationState: "CONFIRMED",
      },
    ],
    taxRecord: {
      id: "tax-ezra",
      npwpNumber: "02.192.483.1-504.000",
      kppName: "KPP Pratama Semarang Tengah",
      registeredDate: "2015-09-01",
      status: "AKTIF",
    },
    branding: {
      numberingPattern: "001/DIR-EZRA/{ROMAN}/{YEAR}",
      footerText: "PT EZRA PRATAMA • IT Enterprise & Engineering Services",
    },
  },
  {
    id: "sbp",
    legalName: "CV SOLUSI BUMI PERSADA",
    businessType: "CV",
    address: "Jl. Pandanaran No. 88, Semarang",
    city: "Semarang",
    phone: "(024) 8312-771",
    email: "contact@solusibumi.co.id",
    website: "https://solusibumi.co.id",
    bankName: "Bank BRI Cabang Pattimura",
    bankAccountNumber: "0022-01-002938-53-0",
    bankAccountHolder: "CV SOLUSI BUMI PERSADA",
    directors: [
      {
        id: "dir-sbp-1",
        fullName: "Bambang Susilo, S.E.",
        position: "Direktur",
        idCardNumber: "3374051504780002",
        taxIdNumber: "81.392.103.5-503.000",
        effectiveFrom: "2017-01-10",
        isSignatory: true,
        deedReference: "Akta Pendirian No. 05 Notaris Bambang S.H.",
      },
    ],
    legalDocuments: [
      {
        id: "leg-sbp-1",
        documentType: "NIB",
        documentNumber: "9120005928172",
        issueDate: "2019-03-12",
        issuingAuthority: "OSS Kemeninves",
        sourceFile: "NIB_CV_Solusi_Bumi_Persada.pdf",
        verificationState: "CONFIRMED",
      },
    ],
    taxRecord: {
      id: "tax-sbp",
      npwpNumber: "81.392.103.5-503.000",
      kppName: "KPP Pratama Semarang Timur",
      registeredDate: "2017-02-01",
      status: "AKTIF",
    },
    branding: {
      numberingPattern: "001/SBP-ADM/{ROMAN}/{YEAR}",
      footerText: "CV SOLUSI BUMI PERSADA • General Procurement & Engineering",
    },
  },
  {
    id: "stigma",
    legalName: "CV STIGMA PRATAMA",
    businessType: "CV",
    address: "Jl. Majapahit No. 210, Semarang",
    city: "Semarang",
    phone: "(024) 6711-209",
    email: "office@stigmapratama.com",
    website: "https://stigmapratama.com",
    bankName: "Bank BNI Cabang Karangayu",
    bankAccountNumber: "0392-817263-001",
    bankAccountHolder: "CV STIGMA PRATAMA",
    directors: [
      {
        id: "dir-stigma-1",
        fullName: "Hendra Wijaya, S.T.",
        position: "Direktur",
        idCardNumber: "3374091908820004",
        taxIdNumber: "65.201.993.2-503.000",
        effectiveFrom: "2020-05-18",
        isSignatory: true,
        deedReference: "Akta Notaris Yulia S.H. No. 19",
      },
    ],
    legalDocuments: [
      {
        id: "leg-stigma-1",
        documentType: "NIB",
        documentNumber: "0220009182736",
        issueDate: "2020-06-01",
        issuingAuthority: "OSS Kemeninves",
        sourceFile: "NIB_CV_Stigma_Pratama.pdf",
        verificationState: "CONFIRMED",
      },
    ],
    taxRecord: {
      id: "tax-stigma",
      npwpNumber: "65.201.993.2-503.000",
      kppName: "KPP Pratama Semarang Selatan",
      registeredDate: "2020-06-15",
      status: "AKTIF",
    },
    branding: {
      numberingPattern: "001/STIGMA/{ROMAN}/{YEAR}",
      footerText: "CV STIGMA PRATAMA • System Integrator & Consulting Services",
    },
  },
];

export const MOCK_PEOPLE: Person[] = [
  {
    id: "person-1",
    fullName: "Agus Setiawan",
    academicTitle: "S.Kom., M.T.",
    currentPrimaryCompanyId: "aos",
    birthPlace: "Semarang",
    birthDate: "1988-08-17",
    lastEducation: "S2",
    major: "Teknik Informatika",
    university: "Universitas Diponegoro",
    totalYearsExperience: 12,
    skills: ["Team Leader", "System Architecture", "IoT Systems", "Fullstack Node/Next.js"],
    certifications: [
      {
        id: "cert-1",
        certificateName: "Certified Software Architect (CSA)",
        issuingBody: "BNSP / LSP Informatika",
        certificateNumber: "REG-CSA-2022-991",
        issueDate: "2022-03-10",
        validUntil: "2027-03-09",
        sourceFile: "Sertifikat_CSA_Agus.pdf",
      },
    ],
    employmentHistory: [
      {
        id: "emp-1",
        companyName: "CV ALFA OMEGA SOLUSINDO",
        role: "Senior Lead Architect",
        status: "Permanent",
        startDate: "2020-01-01",
        sourceDocument: "SK_Pengangkatan_Agus_AOS.pdf",
      },
      {
        id: "emp-2",
        companyName: "PT EZRA PRATAMA",
        role: "Consultant Systems Engineer",
        status: "Consultant",
        startDate: "2017-02-01",
        endDate: "2019-12-31",
        sourceDocument: "Kontrak_Konsultan_Agus_Ezra.pdf",
      },
    ],
    idCardNumber: "3374021708880001",
    taxNumber: "88.291.029.3-503.000",
    cvSourceFile: "CV_Agus_Setiawan_2026.pdf",
    verificationState: "CONFIRMED",
  },
  {
    id: "person-2",
    fullName: "Budi Santoso",
    academicTitle: "M.T.",
    currentPrimaryCompanyId: "ezra",
    birthPlace: "Surakarta",
    birthDate: "1985-04-12",
    lastEducation: "S2",
    major: "Magister Teknik Elektro",
    university: "Institut Teknologi Bandung",
    totalYearsExperience: 15,
    skills: ["Database Engineering", "High Performance Computing", "Procurement Tech Spec"],
    certifications: [
      {
        id: "cert-2",
        certificateName: "PMP® Project Management Professional",
        issuingBody: "PMI Global",
        certificateNumber: "PMP-2021-88192",
        issueDate: "2021-06-20",
        validUntil: "2027-06-19",
        sourceFile: "PMP_Budi_Santoso.pdf",
      },
    ],
    employmentHistory: [
      {
        id: "emp-budi-1",
        companyName: "PT EZRA PRATAMA",
        role: "Chief Technology Advisor",
        status: "Permanent",
        startDate: "2018-05-01",
      },
    ],
    idCardNumber: "3372011204850005",
    taxNumber: "71.928.374.1-502.000",
    cvSourceFile: "CV_Budi_Santoso_PMP.pdf",
    verificationState: "CONFIRMED",
  },
  {
    id: "person-3",
    fullName: "Dewi Lestari",
    academicTitle: "S.T.",
    currentPrimaryCompanyId: "aos",
    birthPlace: "Yogyakarta",
    birthDate: "1992-11-05",
    lastEducation: "S1",
    major: "Sistem Informasi",
    university: "Universitas Gadjah Mada",
    totalYearsExperience: 8,
    skills: ["UI/UX Design", "System Analysis", "Database Querying", "Quality Assurance"],
    certifications: [],
    employmentHistory: [
      {
        id: "emp-dewi-1",
        companyName: "CV ALFA OMEGA SOLUSINDO",
        role: "Senior System Analyst",
        status: "Contract",
        startDate: "2022-02-01",
      },
    ],
    idCardNumber: "3471024511920003",
    taxNumber: "92.182.736.4-541.000",
    cvSourceFile: "CV_Dewi_Lestari_Analyst.pdf",
    verificationState: "CONFIRMED",
  },
];

export const MOCK_EXPERIENCES: CompanyExperience[] = [
  {
    id: "exp-aos-1",
    companyId: "aos",
    projectName: "Kaji Terap Automatic Feeder Berbasis Teknologi IoT",
    clientName: "Dinas Perikanan Kota Semarang",
    location: "Kota Semarang",
    contractNumber: "523/SPK/DISKAN/2024",
    contractDate: "2024-03-15",
    contractValueIDR: 485000000,
    startDate: "2024-03-20",
    endDate: "2024-09-18",
    handoverDate: "2024-09-25",
    completionPercentage: 100,
    procurementCategory: "Konsultansi IT",
    scopeSummary: "Pengembangan hardware automatic feeder berbasis IoT, telemetry sensor, cloud dashboard monitoring, dan pelatihan kelompok pembudidaya ikan.",
    spkSourceFile: "SPK_Automatic_Feeder_Diskan_2024.pdf",
    bastSourceFile: "BAST_Automatic_Feeder_Diskan_2024.pdf",
    spmkSourceFile: "SPMK_Automatic_Feeder_Diskan_2024.pdf",
    relevanceScore: 98,
    verificationState: "CONFIRMED",
  },
  {
    id: "exp-aos-2",
    companyId: "aos",
    projectName: "Pengembangan Sistem Informasi Manajemen Tempat Pelelangan Ikan (SIM-TPI)",
    clientName: "Dinas Kelautan dan Perikanan Provinsi Jawa Tengah",
    location: "Semarang & Pati",
    contractNumber: "027/SPK/DKP-JT/IX/2023",
    contractDate: "2023-09-01",
    contractValueIDR: 320000000,
    startDate: "2023-09-05",
    endDate: "2023-12-15",
    handoverDate: "2023-12-20",
    completionPercentage: 100,
    procurementCategory: "Konsultansi IT",
    scopeSummary: "Aplikasi pencatatan transaksi lelang real-time, integrasi gateway pembayaran, dan modul pelaporan retribusi daerah.",
    spkSourceFile: "SPK_SIM_TPI_DKP_2023.pdf",
    bastSourceFile: "BAST_SIM_TPI_DKP_2023.pdf",
    relevanceScore: 92,
    verificationState: "CONFIRMED",
  },
  {
    id: "exp-ezra-1",
    companyId: "ezra",
    projectName: "Pengadaan Masterplan Smart City & Enterprise Architecture Framework",
    clientName: "Bappeda Kota Semarang",
    location: "Kota Semarang",
    contractNumber: "050/KONTRAK/BAPPEDA/2023",
    contractDate: "2023-04-10",
    contractValueIDR: 890000000,
    startDate: "2023-04-15",
    endDate: "2023-10-15",
    handoverDate: "2023-10-20",
    completionPercentage: 100,
    procurementCategory: "Konsultansi IT",
    scopeSummary: "Penyusunan dokumen masterplan smart city 5 tahunan, integrasi arsitektur SPBE, dan blueprint infrastruktur data center.",
    spkSourceFile: "Kontrak_SmartCity_Bappeda_2023.pdf",
    bastSourceFile: "BAST_SmartCity_Bappeda_2023.pdf",
    relevanceScore: 85,
    verificationState: "CONFIRMED",
  },
];

export const MOCK_COMPLIANCE_EVIDENCE: ComplianceEvidence[] = [
  // Monthly BPE Records 2026 for AOS
  {
    id: "bpe-aos-2026-01",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE PPh 23 / PPN Masa Januari 2026",
    documentNumber: "BPE-992019283-0126",
    taxYear: 2026,
    taxPeriodMonth: 1,
    issueDate: "2026-02-10",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "BPE_AOS_Januari_2026.pdf",
    sourcePage: 1,
    verifiedBy: "Compliance Admin",
  },
  {
    id: "bpe-aos-2026-02",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE Masa Februari 2026",
    documentNumber: "BPE-992019283-0226",
    taxYear: 2026,
    taxPeriodMonth: 2,
    issueDate: "2026-03-12",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "BPE_AOS_Februari_2026.pdf",
  },
  {
    id: "bpe-aos-2026-03",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE Masa Maret 2026",
    documentNumber: "BPE-992019283-0326",
    taxYear: 2026,
    taxPeriodMonth: 3,
    issueDate: "2026-04-10",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "BPE_AOS_Maret_2026.pdf",
  },
  {
    id: "bpe-aos-2026-04",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE Masa April 2026",
    documentNumber: "BPE-992019283-0426",
    taxYear: 2026,
    taxPeriodMonth: 4,
    issueDate: "2026-05-11",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "BPE_AOS_April_2026.pdf",
  },
  {
    id: "bpe-aos-2026-05",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE Masa Mei 2026",
    documentNumber: "BPE-992019283-0526",
    taxYear: 2026,
    taxPeriodMonth: 5,
    issueDate: "2026-06-10",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "BPE_AOS_Mei_2026.pdf",
  },
  {
    id: "bpe-aos-2026-06",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE Masa Juni 2026",
    documentNumber: "BPE-992019283-0626",
    taxYear: 2026,
    taxPeriodMonth: 6,
    issueDate: "2026-07-10",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "BPE_AOS_Juni_2026.pdf",
  },
  {
    id: "bpe-aos-2026-07",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE Masa Juli 2026",
    documentNumber: "BPE-992019283-0726",
    taxYear: 2026,
    taxPeriodMonth: 7,
    issueDate: "2026-08-08",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "BPE_AOS_Juli_2026.pdf",
  },
  {
    id: "bpe-aos-2026-08",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE Masa Agustus 2026",
    documentNumber: "BELUM_ADA",
    taxYear: 2026,
    taxPeriodMonth: 8,
    issueDate: "-",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "DUE",
    sourceFile: "-",
    notes: "BPE bulan Agustus 2026 sedang menunggu konfirmasi pelaporan KPP Pratama.",
  },

  // Recurring Bank Statement Evidence (Annual - Target January)
  {
    id: "bank-aos-2026",
    companyId: "aos",
    evidenceType: "SURAT_KETERANGAN_BANK",
    title: "Surat Keterangan Bank Tahun 2026",
    documentNumber: "B.0192/BJT-SMG/SKB/01/2026",
    issueDate: "2026-01-14",
    validUntil: "2026-12-31",
    targetFrequency: "Annual",
    defaultTargetMonth: "Januari",
    status: "VERIFIED",
    sourceFile: "Surat_Keterangan_Bank_Jateng_AOS_2026.pdf",
    notes: "Bank Jateng Cabang Utama Semarang. Referensi keaktifan rekening.",
  },

  // Annual Tax Report (Annual - Target April)
  {
    id: "spt-aos-2025",
    companyId: "aos",
    evidenceType: "SPT_TAHUNAN",
    title: "Laporan SPT Tahunan Badan Tahun Pajak 2025",
    documentNumber: "SPT-1771-2025-00129",
    taxYear: 2025,
    issueDate: "2026-04-18",
    targetFrequency: "Annual",
    defaultTargetMonth: "April",
    status: "VERIFIED",
    sourceFile: "SPT_Tahunan_Badan_AOS_2025.pdf",
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-1",
    companyId: "aos",
    projectName: "Pengembangan Automatic Feeder IoT Tahap II & Dashboard Analytics",
    clientName: "Dinas Perikanan Kota Semarang",
    clientAddress: "Jl. Kolonel Sugiono No. 2, Semarang",
    location: "Kota Semarang",
    procurementCategory: "Konsultansi IT",
    scopeOfWork: "Penyempurnaan modul sensor telemetry, dashboard pemantauan kondisi air real-time, dan otomasi pemberian pakan pada 20 lokasi budidaya.",
    targetStartDate: "2026-09-01",
    targetEndDate: "2026-12-15",
    assignments: [
      {
        id: "assign-1",
        personId: "person-1",
        proposedPosition: "Team Leader / Software Architect",
        roleDescription: "Mengkoordinasi seluruh tim teknis, merancang arsitektur sistem IoT, dan bertanggung jawab atas deliverables.",
        allocationPercent: 100,
        manMonths: 3.5,
        billingRateIDR: 25000000,
      },
      {
        id: "assign-2",
        personId: "person-3",
        proposedPosition: "System Analyst & QA Lead",
        roleDescription: "Melakukan analisis kebutuhan user, pengujian fitur IoT telemetry, dan dokumentasi user manual.",
        allocationPercent: 100,
        manMonths: 3.5,
        billingRateIDR: 18000000,
      },
    ],
    selectedExperienceIds: ["exp-aos-1", "exp-aos-2"],
    financials: {
      items: [
        {
          id: "fin-1",
          category: "Personnel",
          description: "Team Leader / Software Architect (Agus Setiawan, S.Kom., M.T.)",
          personName: "Agus Setiawan",
          role: "Team Leader",
          quantity: 1,
          unit: "OB",
          durationMonths: 3.5,
          billingRateIDR: 25000000,
          subtotalIDR: 87500000,
        },
        {
          id: "fin-2",
          category: "Personnel",
          description: "System Analyst & QA Lead (Dewi Lestari, S.T.)",
          personName: "Dewi Lestari",
          role: "System Analyst",
          quantity: 1,
          unit: "OB",
          durationMonths: 3.5,
          billingRateIDR: 18000000,
          subtotalIDR: 63000000,
        },
        {
          id: "fin-3",
          category: "Non-Personnel",
          description: "Sewa Telemetry Sensor Kit & Cloud Testing Infrastructure",
          quantity: 1,
          unit: "Paket",
          durationMonths: 3.5,
          billingRateIDR: 15000000,
          subtotalIDR: 15000000,
        },
        {
          id: "fin-4",
          category: "Non-Personnel",
          description: "Biaya Laporan Pendahuluan, Antara & Akhir (Cetak & Dokumentasi)",
          quantity: 1,
          unit: "Paket",
          durationMonths: 1,
          billingRateIDR: 4500000,
          subtotalIDR: 4500000,
        },
      ],
      personnelCostSubtotalIDR: 150500000,
      nonPersonnelCostSubtotalIDR: 19500000,
      directCostSubtotalIDR: 170000000,
      ppnPercent: 11,
      ppnAmountIDR: 18700000,
      grandTotalIDR: 188700000,
      terbilangIDR: "Seratus Delapan Puluh Delapan Juta Tujuh Ratus Ribu Rupiah",
    },
    status: "Draft",
  },
];

export const MOCK_CONFLICTS: ConflictAlert[] = [
  {
    id: "conf-1",
    severity: "CRITICAL",
    entityName: "Direktur Signatory CV ALFA OMEGA SOLUSINDO",
    field: "Director Name & Deed Match",
    message: "Terdapat perbedaan gelar akademik pada nama Direktur di Akta Pendirian (Ir. Agus Wahyudi) vs Form Legalitas Sistem (Agus Wahyudi, S.T.).",
    sourceA: "Akta Pendirian No. 12 Notaris Hendra S.H. (2018)",
    sourceB: "Profile Form Import NIB OSS (2019)",
    status: "UNRESOLVED",
  },
  {
    id: "conf-2",
    severity: "HIGH",
    entityName: "Compliance Evidence BPE",
    field: "Monthly BPE August 2026",
    message: "BPE Bulan Agustus 2026 belum diunggah atau belum terkonfirmasi oleh KPP Pratama. Dokumen prakualifikasi membutuhkan bukti bayar pajak 3 bulan terakhir.",
    sourceA: "Compliance Tax Repository Checklist",
    sourceB: "Syarat Prakualifikasi Pengadaan DKP 2026",
    status: "UNRESOLVED",
  },
];
