import {
  Company,
  Person,
  CompanyExperience,
  ComplianceEvidence,
  Project,
  ConflictAlert,
} from "@/types/procurement";

export const MOCK_COMPANIES: Company[] = [
  {
    id: "aos",
    legalName: "CV ALFA OMEGA SOLUSINDO",
    businessType: "CV",
    address: "Jl. Candi Penataran A No. 24 Bambankerep",
    city: "Semarang",
    phone: "085640169851",
    email: "alfaomegasolusindo@gmail.com",
    website: "https://alfaomegasolusindo.co.id",
    bankName: "Bank Jateng",
    bankAccountNumber: "1-003-99281-2",
    bankAccountHolder: "CV ALFA OMEGA SOLUSINDO",
    directors: [
      {
        id: "dir-aos-1",
        fullName: "TITIK ENDANGNINGSIH, SE",
        position: "Direktur",
        idCardNumber: "3198768658860",
        taxIdNumber: "24.526.431.8-261.000",
        effectiveFrom: "2018-03-15",
        isSignatory: true,
        deedReference: "Akta Notaris Pendirian CV Alfa Omega Solusindo",
      },
    ],
    legalDocuments: [
      {
        id: "leg-aos-1",
        documentType: "NIB",
        documentNumber: "9120003921822",
        issueDate: "2019-06-10",
        issuingAuthority: "OSS Republik Indonesia",
        sourceFile: "NIB_CV_Alfa_Omega_Solusindo.pdf",
        verificationState: "CONFIRMED",
      },
      {
        id: "leg-aos-2",
        documentType: "SBU",
        documentNumber: "SBU-IT-2024-9982",
        issueDate: "2024-01-15",
        validUntil: "2027-01-14",
        issuingAuthority: "LPJK / Kemenkominfo",
        sourceFile: "SBU_AOS_2024.pdf",
        verificationState: "CONFIRMED",
      },
    ],
    taxRecord: {
      id: "tax-aos",
      npwpNumber: "24.526.431.8-261.000",
      kppName: "KPP Pratama Semarang Barat",
      registeredDate: "2018-04-01",
      status: "AKTIF",
    },
    branding: {
      numberingPattern: "01 / SP / AOS / VIII / 2026",
      footerText: "CV ALFA OMEGA SOLUSINDO • Solutions & Digital Innovation",
    },
  },
  {
    id: "stigma",
    legalName: "CV STIGMA PRATAMA",
    businessType: "CV",
    address: "Jl. Tapak Sari I Tugurejo Tugu, Kota Semarang - 50151",
    city: "Semarang",
    phone: "081326824441",
    email: "stigmapratama@gmail.com",
    website: "https://stigmapratama.com",
    bankName: "Bank BNI",
    bankAccountNumber: "0392-817263-001",
    bankAccountHolder: "CV STIGMA PRATAMA",
    directors: [
      {
        id: "dir-stigma-1",
        fullName: "BUDI SANTOSO, S.Sos",
        position: "Direktur",
        idCardNumber: "302895013335",
        taxIdNumber: "30.010.105.7-150.000",
        effectiveFrom: "2020-05-18",
        isSignatory: true,
        deedReference: "Akta Notaris Pendirian CV Stigma Pratama",
      },
    ],
    legalDocuments: [
      {
        id: "leg-stigma-1",
        documentType: "NIB",
        documentNumber: "0220009182736",
        issueDate: "2020-06-01",
        issuingAuthority: "OSS Kemeninves",
        sourceFile: "NIB_CV_Stigma_Pratama.pdf",
        verificationState: "CONFIRMED",
      },
    ],
    taxRecord: {
      id: "tax-stigma",
      npwpNumber: "30.010.105.7-150.000",
      kppName: "KPP Pratama Semarang Selatan",
      registeredDate: "2020-06-15",
      status: "AKTIF",
    },
    branding: {
      numberingPattern: "01 / SP / DP / IV / 2026",
      footerText: "CV STIGMA PRATAMA • System Integrator & Consulting Services",
    },
  },
  {
    id: "ezra",
    legalName: "PT EZRA PRATAMA",
    businessType: "PT",
    address: "Jl. Candisari III RT.001 RW.005 Bambankerep Ngaliyan",
    city: "Semarang",
    phone: "024-76674166",
    email: "ezrapratama@gmail.com",
    website: "https://ezrapratama.co.id",
    bankName: "Bank Mandiri",
    bankAccountNumber: "135-00-1928374-1",
    bankAccountHolder: "PT EZRA PRATAMA",
    directors: [
      {
        id: "dir-ezra-1",
        fullName: "DONI YOHANES, S.Kom, M.Kom",
        position: "Direktur Utama",
        idCardNumber: "331470019685",
        taxIdNumber: "28.670.251.2-065.000",
        effectiveFrom: "2015-08-10",
        isSignatory: true,
        deedReference: "Akta Notaris Pendirian PT Ezra Pratama",
      },
    ],
    legalDocuments: [
      {
        id: "leg-ezra-1",
        documentType: "NIB",
        documentNumber: "8120001928374",
        issueDate: "2018-11-20",
        issuingAuthority: "OSS Kemeninves",
        sourceFile: "NIB_PT_Ezra_Pratama.pdf",
        verificationState: "CONFIRMED",
      },
    ],
    taxRecord: {
      id: "tax-ezra",
      npwpNumber: "28.670.251.2-065.000",
      kppName: "KPP Pratama Semarang Tengah",
      registeredDate: "2015-09-01",
      status: "AKTIF",
    },
    branding: {
      numberingPattern: "01 / SP / DP / II / 2026",
      footerText: "PT EZRA PRATAMA • E-Government Specialist & IT Consultant",
    },
  },
  {
    id: "sbp",
    legalName: "CV SOLUSI BUMI PERSADA",
    businessType: "CV",
    address: "JL. Sinar Waluyo No. 120 A, Kelurahan Kedungmundu, Kecamatan Tembalang",
    city: "Semarang",
    phone: "(024) 8312-771",
    email: "info@multisolusi.info",
    website: "http://www.multisolusi.info",
    bankName: "Bank BRI",
    bankAccountNumber: "0022-01-002938-53-0",
    bankAccountHolder: "CV SOLUSI BUMI PERSADA",
    directors: [
      {
        id: "dir-sbp-1",
        fullName: "Agus Hartanto, S.kom., M.Kom.",
        position: "Direktur",
        idCardNumber: "3374051504780002",
        taxIdNumber: "81.392.103.5-503.000",
        effectiveFrom: "2017-01-10",
        isSignatory: true,
        deedReference: "Akta Notaris Pendirian CV Solusi Bumi Persada",
      },
    ],
    legalDocuments: [
      {
        id: "leg-sbp-1",
        documentType: "NIB",
        documentNumber: "9120005928172",
        issueDate: "2019-03-12",
        issuingAuthority: "OSS Kemeninves",
        sourceFile: "NIB_CV_Solusi_Bumi_Persada.pdf",
        verificationState: "CONFIRMED",
      },
    ],
    taxRecord: {
      id: "tax-sbp",
      npwpNumber: "81.392.103.5-503.000",
      kppName: "KPP Pratama Semarang Timur",
      registeredDate: "2017-02-01",
      status: "AKTIF",
    },
    branding: {
      numberingPattern: "01 / DINSOS / SIDAKSOS / V / 2023",
      footerText: "CV SOLUSI BUMI PERSADA • General Procurement & Engineering",
    },
  },
];

export const MOCK_PEOPLE: Person[] = [
  {
    id: "person-1",
    fullName: "Agus Setiawan",
    academicTitle: "S.Kom., M.T.",
    currentPrimaryCompanyId: "aos",
    birthPlace: "Semarang",
    birthDate: "1988-08-17",
    lastEducation: "S2",
    major: "Teknik Informatika",
    university: "Universitas Diponegoro",
    totalYearsExperience: 12,
    skills: ["Team Leader", "System Architecture", "IoT Systems", "Fullstack Node/Next.js"],
    certifications: [
      {
        id: "cert-1",
        certificateName: "Certified Software Architect (CSA)",
        issuingBody: "BNSP / LSP Informatika",
        certificateNumber: "REG-CSA-2022-991",
        issueDate: "2022-03-10",
        validUntil: "2027-03-09",
        sourceFile: "Sertifikat_CSA_Agus.pdf",
      },
    ],
    employmentHistory: [
      {
        id: "emp-1",
        companyName: "CV ALFA OMEGA SOLUSINDO",
        role: "Senior Lead Architect",
        status: "Permanent",
        startDate: "2020-01-01",
        sourceDocument: "SK_Pengangkatan_Agus_AOS.pdf",
      },
      {
        id: "emp-2",
        companyName: "PT EZRA PRATAMA",
        role: "Consultant Systems Engineer",
        status: "Consultant",
        startDate: "2017-02-01",
        endDate: "2019-12-31",
        sourceDocument: "Kontrak_Konsultan_Agus_Ezra.pdf",
      },
    ],
    idCardNumber: "3374021708880001",
    taxNumber: "88.291.029.3-503.000",
    cvSourceFile: "CV_Agus_Setiawan_2026.pdf",
    verificationState: "CONFIRMED",
  },
  {
    id: "person-2",
    fullName: "Budi Santoso",
    academicTitle: "M.T.",
    currentPrimaryCompanyId: "ezra",
    birthPlace: "Surakarta",
    birthDate: "1985-04-12",
    lastEducation: "S2",
    major: "Magister Teknik Elektro",
    university: "Institut Teknologi Bandung",
    totalYearsExperience: 15,
    skills: ["Database Engineering", "High Performance Computing", "Procurement Tech Spec"],
    certifications: [
      {
        id: "cert-2",
        certificateName: "PMP® Project Management Professional",
        issuingBody: "PMI Global",
        certificateNumber: "PMP-2021-88192",
        issueDate: "2021-06-20",
        validUntil: "2027-06-19",
        sourceFile: "PMP_Budi_Santoso.pdf",
      },
    ],
    employmentHistory: [
      {
        id: "emp-budi-1",
        companyName: "PT EZRA PRATAMA",
        role: "Chief Technology Advisor",
        status: "Permanent",
        startDate: "2018-05-01",
      },
    ],
    idCardNumber: "3372011204850005",
    taxNumber: "71.928.374.1-502.000",
    cvSourceFile: "CV_Budi_Santoso_PMP.pdf",
    verificationState: "CONFIRMED",
  },
  {
    id: "person-3",
    fullName: "Dewi Lestari",
    academicTitle: "S.T.",
    currentPrimaryCompanyId: "aos",
    birthPlace: "Yogyakarta",
    birthDate: "1992-11-05",
    lastEducation: "S1",
    major: "Sistem Informasi",
    university: "Universitas Gadjah Mada",
    totalYearsExperience: 8,
    skills: ["UI/UX Design", "System Analysis", "Database Querying", "Quality Assurance"],
    certifications: [],
    employmentHistory: [
      {
        id: "emp-dewi-1",
        companyName: "CV ALFA OMEGA SOLUSINDO",
        role: "Senior System Analyst",
        status: "Contract",
        startDate: "2022-02-01",
      },
    ],
    idCardNumber: "3471024511920003",
    taxNumber: "92.182.736.4-541.000",
    cvSourceFile: "CV_Dewi_Lestari_Analyst.pdf",
    verificationState: "CONFIRMED",
  },
  {
    id: "person-stigma-0",
    fullName: "Affandy Ichsan",
    academicTitle: "S.Kom.",
    currentPrimaryCompanyId: "stigma",
    birthPlace: "Semarang",
    birthDate: "1988-03-12",
    lastEducation: "S1",
    major: "Teknik Informatika",
    university: "Universitas Dian Nuswantoro",
    totalYearsExperience: 12,
    skills: ["Team Leader", "Kecerdasan Buatan / Computer Vision", "IoT Motion Telemetry", "Hardware Integration"],
    certifications: [
      {
        id: "cert-affandy-1",
        certificateName: "Certified AI Computer Vision & IoT Specialist",
        issuingBody: "BNSP / LSP Informatika",
        certificateNumber: "REG-AI-2023-118",
        issueDate: "2023-05-10",
        sourceFile: "2. Penawaran Teknis - Kualifikasi Tenaga Ahli - CV STIGMA PRATAMA.docx",
      },
    ],
    employmentHistory: [
      {
        id: "emp-affandy-1",
        companyName: "CV STIGMA PRATAMA",
        role: "Team Leader / Ahli Kecerdasan Buatan",
        status: "Permanent",
        startDate: "2020-05-01",
        sourceDocument: "4. Surat Penugasan Personil - CV STIGMA PRATAMA.docx",
      },
    ],
    idCardNumber: "3374021203880001",
    taxNumber: "75.821.902.1-503.000",
    cvSourceFile: "4. Surat Penugasan Personil - CV STIGMA PRATAMA.docx",
    verificationState: "CONFIRMED",
  },
  {
    id: "person-stigma-1",
    fullName: "Dyan Sinung Prabowo",
    academicTitle: "S.Kom.",
    currentPrimaryCompanyId: "stigma",
    birthPlace: "Rembang",
    birthDate: "2000-09-25",
    lastEducation: "SMK",
    major: "Teknik Komputer & Jaringan",
    university: "SMK Negeri 1 Rembang",
    totalYearsExperience: 4,
    skills: ["Operator Komputer", "Administrasi Proyek", "Dokumentasi Kontrak"],
    certifications: [],
    employmentHistory: [
      {
        id: "emp-dyan-1",
        companyName: "PT. EZRA PRATAMA",
        role: "Operator Komputer / Administrasi",
        status: "Contract",
        startDate: "2022-06-01",
        endDate: "2022-08-31",
        sourceDocument: "3. Curriculum Vitae - DYAN SINUNG PRABOWO - CV STIGMA PRATAMA.docx",
      },
      {
        id: "emp-dyan-2",
        companyName: "CV STIGMA PRATAMA",
        role: "Tenaga Administrasi",
        status: "Contract",
        startDate: "2023-01-01",
        sourceDocument: "3. Curriculum Vitae - DYAN SINUNG PRABOWO - CV STIGMA PRATAMA.docx",
      },
    ],
    idCardNumber: "3317012509000002",
    taxNumber: "75.821.902.1-503.000",
    cvSourceFile: "3. Curriculum Vitae - DYAN SINUNG PRABOWO - CV STIGMA PRATAMA.docx",
    verificationState: "CONFIRMED",
  },
  {
    id: "person-stigma-2",
    fullName: "Eri Nur Sofa",
    academicTitle: "S.Kom.",
    currentPrimaryCompanyId: "stigma",
    birthPlace: "Semarang",
    birthDate: "1992-08-22",
    lastEducation: "S1",
    major: "Teknik Informatika",
    university: "Universitas Semarang (Lulus 2019)",
    totalYearsExperience: 7,
    skills: ["Quality Engineer", "Programmer", "IoT Smart Monitoring", "Web Developer"],
    certifications: [
      {
        id: "cert-eri-1",
        certificateName: "Pelatihan Pengembangan Aplikasi & Quality Assurance",
        issuingBody: "Universitas Semarang",
        certificateNumber: "REG-QA-2020-001",
        issueDate: "2020-02-15",
        sourceFile: "3. Curriculum Vitae - ERI NUR SOFA - CV STIGMA PRATAMA.docx",
      },
    ],
    employmentHistory: [
      {
        id: "emp-eri-1",
        companyName: "CV. Solusi Bumi Persada",
        role: "Programmer Aplikasi SIDAKSOS",
        status: "Permanent",
        startDate: "2020-03-01",
        endDate: "2020-05-31",
        sourceDocument: "B.1179/027.1/III/2020",
      },
      {
        id: "emp-eri-2",
        companyName: "PT. EZRA PRATAMA",
        role: "Staf Ahli Pemeliharaan Software & Hardware",
        status: "Contract",
        startDate: "2019-02-01",
        endDate: "2019-12-31",
        sourceDocument: "08/SI/PEMEL/II/2019",
      },
      {
        id: "emp-eri-3",
        companyName: "CV STIGMA PRATAMA",
        role: "Tenaga Sistem Keamanan / Programmer",
        status: "Contract",
        startDate: "2021-01-01",
        sourceDocument: "4. Surat Penugasan Personil - CV STIGMA PRATAMA.docx",
      },
    ],
    idCardNumber: "3374022208920003",
    taxNumber: "81.928.374.5-503.000",
    cvSourceFile: "3. Curriculum Vitae - ERI NUR SOFA - CV STIGMA PRATAMA.docx",
    verificationState: "CONFIRMED",
  },
];

export const MOCK_EXPERIENCES: CompanyExperience[] = [
  {
    id: "exp-aos-1",
    companyId: "aos",
    projectName: "Kaji Terap Automatic Feeder Berbasis Teknologi IoT",
    clientName: "Dinas Perikanan Kota Semarang",
    location: "Kota Semarang",
    contractNumber: "523/SPK/DISKAN/2024",
    contractDate: "2024-03-15",
    contractValueIDR: 485000000,
    startDate: "2024-03-20",
    endDate: "2024-09-18",
    handoverDate: "2024-09-25",
    completionPercentage: 100,
    procurementCategory: "Konsultansi IT",
    scopeSummary: "Pengembangan hardware automatic feeder berbasis IoT, telemetry sensor, cloud dashboard monitoring, dan pelatihan kelompok pembudidaya ikan.",
    spkSourceFile: "SPK_Automatic_Feeder_Diskan_2024.pdf",
    bastSourceFile: "BAST_Automatic_Feeder_Diskan_2024.pdf",
    spmkSourceFile: "SPMK_Automatic_Feeder_Diskan_2024.pdf",
    relevanceScore: 98,
    verificationState: "CONFIRMED",
  },
  {
    id: "exp-aos-2",
    companyId: "aos",
    projectName: "Pengembangan Sistem Informasi Manajemen Tempat Pelelangan Ikan (SIM-TPI)",
    clientName: "Dinas Kelautan dan Perikanan Provinsi Jawa Tengah",
    location: "Semarang & Pati",
    contractNumber: "027/SPK/DKP-JT/IX/2023",
    contractDate: "2023-09-01",
    contractValueIDR: 320000000,
    startDate: "2023-09-05",
    endDate: "2023-12-15",
    handoverDate: "2023-12-20",
    completionPercentage: 100,
    procurementCategory: "Konsultansi IT",
    scopeSummary: "Aplikasi pencatatan transaksi lelang real-time, integrasi gateway pembayaran, dan modul pelaporan retribusi daerah.",
    spkSourceFile: "SPK_SIM_TPI_DKP_2023.pdf",
    bastSourceFile: "BAST_SIM_TPI_DKP_2023.pdf",
    relevanceScore: 92,
    verificationState: "CONFIRMED",
  },
  {
    id: "exp-ezra-1",
    companyId: "ezra",
    projectName: "Pengadaan Masterplan Smart City & Enterprise Architecture Framework",
    clientName: "Bappeda Kota Semarang",
    location: "Kota Semarang",
    contractNumber: "050/KONTRAK/BAPPEDA/2023",
    contractDate: "2023-04-10",
    contractValueIDR: 890000000,
    startDate: "2023-04-15",
    endDate: "2023-10-15",
    handoverDate: "2023-10-20",
    completionPercentage: 100,
    procurementCategory: "Konsultansi IT",
    scopeSummary: "Penyusunan dokumen masterplan smart city 5 tahunan, integrasi arsitektur SPBE, dan blueprint infrastruktur data center.",
    spkSourceFile: "Kontrak_SmartCity_Bappeda_2023.pdf",
    bastSourceFile: "BAST_SmartCity_Bappeda_2023.pdf",
    relevanceScore: 85,
    verificationState: "CONFIRMED",
  },
  {
    id: "exp-stigma-1",
    companyId: "stigma",
    projectName: "Pengembangan Sistem Informasi e-File & Manajemen Arsip Kepegawaian",
    clientName: "Badan Kepegawaian Daerah (BKD) Kota Semarang",
    location: "Kota Semarang",
    contractNumber: "800/SPK/BKD/2022",
    contractDate: "2022-06-15",
    contractValueIDR: 195000000,
    startDate: "2022-06-20",
    endDate: "2022-10-20",
    handoverDate: "2022-10-25",
    completionPercentage: 100,
    procurementCategory: "Konsultansi IT",
    scopeSummary: "Digitalisasi arsip ASN, modul enkripsi berkas digital, OCR dokumen riwayat jabatan, dan integrasi Single Identity.",
    spkSourceFile: "5.a. Scan Kontrak BKD Pengembangan e File 2022 - CV STIGMA PRATAMA.pdf",
    bastSourceFile: "5.a. Scan Kontrak BKD Pengembangan e File 2022 - CV STIGMA PRATAMA.pdf",
    relevanceScore: 95,
    verificationState: "CONFIRMED",
  },
  {
    id: "exp-stigma-2",
    companyId: "stigma",
    projectName: "Pengembangan Fitur Serta Fungsi Aplikasi SIPU (Sistem Informasi Pekerjaan Umum)",
    clientName: "Dinas Pekerjaan Umum (DPU) Kota Semarang",
    location: "Kota Semarang",
    contractNumber: "600/SPK/DPU/2023",
    contractDate: "2023-05-10",
    contractValueIDR: 245000000,
    startDate: "2023-05-15",
    endDate: "2023-09-15",
    handoverDate: "2023-09-20",
    completionPercentage: 100,
    procurementCategory: "Konsultansi IT",
    scopeSummary: "Upgrade modul pelaporan jalan & drainase real-time, integrasi peta GIS spasial, dan dashboard progres monitoring lapangan.",
    spkSourceFile: "5.b. Scan Kontrak DPU Fitur serta fungsi SIPU - CV STIGMA PRATAMA.pdf",
    bastSourceFile: "5.b. Scan Kontrak DPU Fitur serta fungsi SIPU - CV STIGMA PRATAMA.pdf",
    relevanceScore: 92,
    verificationState: "CONFIRMED",
  },
];

export const MOCK_COMPLIANCE_EVIDENCE: ComplianceEvidence[] = [
  // Monthly BPE Records 2026 for AOS
  {
    id: "bpe-aos-2026-01",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE PPh 23 / PPN Masa Januari 2026",
    documentNumber: "BPE-992019283-0126",
    taxYear: 2026,
    taxPeriodMonth: 1,
    issueDate: "2026-02-10",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "BPE_AOS_Januari_2026.pdf",
    sourcePage: 1,
    verifiedBy: "Compliance Admin",
  },
  {
    id: "bpe-aos-2026-02",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE Masa Februari 2026",
    documentNumber: "BPE-992019283-0226",
    taxYear: 2026,
    taxPeriodMonth: 2,
    issueDate: "2026-03-12",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "BPE_AOS_Februari_2026.pdf",
  },
  {
    id: "bpe-aos-2026-03",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE Masa Maret 2026",
    documentNumber: "BPE-992019283-0326",
    taxYear: 2026,
    taxPeriodMonth: 3,
    issueDate: "2026-04-10",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "BPE_AOS_Maret_2026.pdf",
  },
  {
    id: "bpe-aos-2026-04",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE Masa April 2026",
    documentNumber: "BPE-992019283-0426",
    taxYear: 2026,
    taxPeriodMonth: 4,
    issueDate: "2026-05-11",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "BPE_AOS_April_2026.pdf",
  },
  {
    id: "bpe-aos-2026-05",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE Masa Mei 2026",
    documentNumber: "BPE-992019283-0526",
    taxYear: 2026,
    taxPeriodMonth: 5,
    issueDate: "2026-06-10",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "BPE_AOS_Mei_2026.pdf",
  },
  {
    id: "bpe-aos-2026-06",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE Masa Juni 2026",
    documentNumber: "BPE-992019283-0626",
    taxYear: 2026,
    taxPeriodMonth: 6,
    issueDate: "2026-07-10",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "BPE_AOS_Juni_2026.pdf",
  },
  {
    id: "bpe-aos-2026-07",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE Masa Juli 2026",
    documentNumber: "BPE-992019283-0726",
    taxYear: 2026,
    taxPeriodMonth: 7,
    issueDate: "2026-08-08",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "BPE_AOS_Juli_2026.pdf",
  },
  {
    id: "bpe-aos-2026-08",
    companyId: "aos",
    evidenceType: "BPE",
    title: "BPE Masa Agustus 2026",
    documentNumber: "BELUM_ADA",
    taxYear: 2026,
    taxPeriodMonth: 8,
    issueDate: "-",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "DUE",
    sourceFile: "-",
    notes: "BPE bulan Agustus 2026 sedang menunggu konfirmasi pelaporan KPP Pratama.",
  },

  // Recurring Bank Statement Evidence (Annual - Target January)
  {
    id: "bank-aos-2026",
    companyId: "aos",
    evidenceType: "SURAT_KETERANGAN_BANK",
    title: "Surat Keterangan Bank Tahun 2026",
    documentNumber: "B.0192/BJT-SMG/SKB/01/2026",
    issueDate: "2026-01-14",
    validUntil: "2026-12-31",
    targetFrequency: "Annual",
    defaultTargetMonth: "Januari",
    status: "VERIFIED",
    sourceFile: "Surat_Keterangan_Bank_Jateng_AOS_2026.pdf",
    notes: "Bank Jateng Cabang Utama Semarang. Referensi keaktifan rekening.",
  },

  // Annual Tax Report (Annual - Target April)
  {
    id: "spt-aos-2025",
    companyId: "aos",
    evidenceType: "SPT_TAHUNAN",
    title: "Laporan SPT Tahunan Badan Tahun Pajak 2025",
    documentNumber: "SPT-1771-2025-00129",
    taxYear: 2025,
    issueDate: "2026-04-18",
    targetFrequency: "Annual",
    defaultTargetMonth: "April",
    status: "VERIFIED",
    sourceFile: "SPT_Tahunan_Badan_AOS_2025.pdf",
  },

  // Stigma Pratama Compliance Evidence from Folder 3
  {
    id: "bpe-stigma-2026-01",
    companyId: "stigma",
    evidenceType: "BPE",
    title: "BPE Masa Januari 2026 - CV STIGMA PRATAMA",
    documentNumber: "BPE-STIGMA-2026-01",
    taxYear: 2026,
    taxPeriodMonth: 1,
    issueDate: "2026-02-10",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "4.a BPE Januari 2026 - CV STIGMA PRATAMA.jpg",
  },
  {
    id: "bpe-stigma-2026-02",
    companyId: "stigma",
    evidenceType: "BPE",
    title: "BPE Masa Februari 2026 - CV STIGMA PRATAMA",
    documentNumber: "BPE-STIGMA-2026-02",
    taxYear: 2026,
    taxPeriodMonth: 2,
    issueDate: "2026-03-11",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "4.b BPE Februari 2026 - CV STIGMA PRATAMA.jpg",
  },
  {
    id: "bpe-stigma-2026-03",
    companyId: "stigma",
    evidenceType: "BPE",
    title: "BPE Masa Maret 2026 - CV STIGMA PRATAMA",
    documentNumber: "BPE-STIGMA-2026-03",
    taxYear: 2026,
    taxPeriodMonth: 3,
    issueDate: "2026-04-10",
    targetFrequency: "Monthly",
    defaultTargetMonth: "Setiap Bulan",
    status: "VERIFIED",
    sourceFile: "4.c BPE Maret 2026 - CV STIGMA PRATAMA.jpg",
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-aos-1",
    companyId: "aos",
    projectName: "Pekerjaan Kaji Terap Automatic Feeder Berbasis Teknologi IoT Pada Balai Benih Ikan Dinas Perikanan Kota Semarang Tahun Anggaran 2026",
    clientName: "Pejabat Pengadaan Pada Dinas Perikanan Kota Semarang",
    clientAddress: "Dinas Perikanan Kota Semarang, Semarang",
    location: "Kota Semarang",
    procurementCategory: "Konsultansi IT",
    scopeOfWork: "Pekerjaan Kaji Terap Automatic Feeder Berbasis Teknologi IoT Pada Balai Benih Ikan Dinas Perikanan Kota Semarang Tahun Anggaran 2026",
    targetStartDate: "2026-08-13",
    targetEndDate: "2026-11-11",
    documentNumber: "01 / SP / AOS / VIII / 2026",
    documentDate: "2026-08-13",
    procurementRefNo: "PL06A/02/PP-Perikanan/VIII/2026",
    executionDays: 90,
    validityDays: 90,
    assignments: [
      {
        id: "assign-aos-1",
        personId: "person-1",
        proposedPosition: "Team Leader / Tenaga Ahli IoT",
        roleDescription: "Mengkoordinasi pekerjaan kaji terap automatic feeder berbasis IoT.",
        allocationPercent: 100,
        manMonths: 3,
        billingRateIDR: 25000000,
      },
    ],
    selectedExperienceIds: ["exp-aos-1"],
    financials: {
      items: [
        {
          id: "fin-aos-1",
          category: "Personnel",
          description: "Tenaga Ahli IoT & System Architect",
          quantity: 1,
          unit: "OB",
          durationMonths: 3,
          billingRateIDR: 25000000,
          subtotalIDR: 75000000,
        },
        {
          id: "fin-aos-2",
          category: "Non-Personnel",
          description: "Perangkat Automatic Feeder IoT & Testing Equipment",
          quantity: 1,
          unit: "Paket",
          durationMonths: 1,
          billingRateIDR: 14450176,
          subtotalIDR: 14450176,
        },
      ],
      personnelCostSubtotalIDR: 75000000,
      nonPersonnelCostSubtotalIDR: 14450176,
      directCostSubtotalIDR: 89450176,
      ppnPercent: 11,
      ppnAmountIDR: 9839324,
      grandTotalIDR: 99289500,
      terbilangIDR: "Sembilan Puluh Sembilan Juta Dua Ratus Delapan Puluh Sembilan Ribu Lima Ratus Rupiah",
    },
    status: "Approved",
  },
  {
    id: "proj-stigma-1",
    companyId: "stigma",
    projectName: "Pekerjaan Kaji Terap Smart Monitoring Berbasis IoT Motion Pada Balai Benih Ikan Dinas Perikanan Kota Semarang Tahun Anggaran 2026",
    clientName: "Pejabat Pengadaan Pada Dinas Perikanan Kota Semarang",
    clientAddress: "Dinas Perikanan Kota Semarang, Semarang",
    location: "Kota Semarang",
    procurementCategory: "Konsultansi IT",
    scopeOfWork: "Pekerjaan Kaji Terap Smart Monitoring Berbasis IoT Motion Pada Balai Benih Ikan Dinas Perikanan Kota Semarang Tahun Anggaran 2026",
    targetStartDate: "2026-04-15",
    targetEndDate: "2026-08-13",
    documentNumber: "01 / SP / DP / IV / 2026",
    documentDate: "2026-04-15",
    procurementRefNo: "PL02A/02/PP-Perikanan/IV/2026",
    executionDays: 120,
    validityDays: 120,
    assignments: [
      {
        id: "assign-stigma-1",
        personId: "person-2",
        proposedPosition: "System Integrator Lead",
        roleDescription: "Mengkoordinasi implementasi smart monitoring berbasis IoT Motion.",
        allocationPercent: 100,
        manMonths: 4,
        billingRateIDR: 18000000,
      },
    ],
    selectedExperienceIds: [],
    financials: {
      items: [
        {
          id: "fin-stigma-1",
          category: "Personnel",
          description: "Team Leader Ahli Kecerdasan Buatan / Computer Vision",
          personName: "Affandy Ichsan, S.Kom.",
          role: "Team Leader",
          quantity: 1,
          unit: "OB",
          durationMonths: 4,
          billingRateIDR: 8875000,
          subtotalIDR: 35500000,
        },
        {
          id: "fin-stigma-2",
          category: "Personnel",
          description: "Tenaga Ahli Sistem Keamanan / Teknologi Informasi",
          personName: "Eri Nur Sofa, S.Kom.",
          role: "Programmer & Quality Engineer",
          quantity: 1,
          unit: "OB",
          durationMonths: 4,
          billingRateIDR: 8875000,
          subtotalIDR: 35500000,
        },
        {
          id: "fin-stigma-3",
          category: "Personnel",
          description: "Tenaga Pendukung Operator Komputer",
          personName: "Dyan Sinung Prabowo, S.Kom.",
          role: "Operator Komputer",
          quantity: 1,
          unit: "OB",
          durationMonths: 1,
          billingRateIDR: 3700000,
          subtotalIDR: 3700000,
        },
        {
          id: "fin-stigma-4",
          category: "Non-Personnel",
          description: "Modul Hardware",
          quantity: 1,
          unit: "Pcs",
          durationMonths: 1,
          billingRateIDR: 3750000,
          subtotalIDR: 3750000,
        },
        {
          id: "fin-stigma-5",
          category: "Non-Personnel",
          description: "Modul Camera",
          quantity: 1,
          unit: "Set",
          durationMonths: 1,
          billingRateIDR: 2000000,
          subtotalIDR: 2000000,
        },
        {
          id: "fin-stigma-6",
          category: "Non-Personnel",
          description: "Modul Software Infrastruktur Server",
          quantity: 1,
          unit: "Pcs",
          durationMonths: 1,
          billingRateIDR: 4000000,
          subtotalIDR: 4000000,
        },
        {
          id: "fin-stigma-7",
          category: "Non-Personnel",
          description: "Biaya Komunikasi",
          quantity: 1,
          unit: "Paket",
          durationMonths: 1,
          billingRateIDR: 300000,
          subtotalIDR: 300000,
        },
        {
          id: "fin-stigma-8",
          category: "Non-Personnel",
          description: "Biaya Transportasi",
          quantity: 1,
          unit: "Paket",
          durationMonths: 1,
          billingRateIDR: 2750000,
          subtotalIDR: 2750000,
        },
        {
          id: "fin-stigma-9",
          category: "Non-Personnel",
          description: "Kertas HVS A4",
          quantity: 4,
          unit: "Rim",
          durationMonths: 1,
          billingRateIDR: 50000,
          subtotalIDR: 200000,
        },
        {
          id: "fin-stigma-10",
          category: "Non-Personnel",
          description: "Tinta Printer",
          quantity: 4,
          unit: "Buah",
          durationMonths: 1,
          billingRateIDR: 100000,
          subtotalIDR: 400000,
        },
        {
          id: "fin-stigma-11",
          category: "Non-Personnel",
          description: "Laporan Pendahuluan",
          quantity: 5,
          unit: "Buku",
          durationMonths: 1,
          billingRateIDR: 80000,
          subtotalIDR: 400000,
        },
        {
          id: "fin-stigma-12",
          category: "Non-Personnel",
          description: "Laporan Akhir",
          quantity: 5,
          unit: "Buku",
          durationMonths: 1,
          billingRateIDR: 100000,
          subtotalIDR: 500000,
        },
        {
          id: "fin-stigma-13",
          category: "Non-Personnel",
          description: "Manual Book",
          quantity: 5,
          unit: "Buku",
          durationMonths: 1,
          billingRateIDR: 100000,
          subtotalIDR: 500000,
        },
      ],
      personnelCostSubtotalIDR: 74700000,
      nonPersonnelCostSubtotalIDR: 14800000,
      directCostSubtotalIDR: 89500000,
      ppnPercent: 11,
      ppnAmountIDR: 9845000,
      grandTotalIDR: 99345000,
      terbilangIDR: "Sembilan Puluh Sembilan Juta Tiga Ratus Empat Puluh Lima Ribu Rupiah",
    },
    status: "Approved",
  },
  {
    id: "proj-ezra-1",
    companyId: "ezra",
    projectName: "Pekerjaan Kaji Terap Rekam Kualitas Air Budidaya Ikan Pada Balai Benih Ikan Dinas Perikanan Kota Semarang Tahun Anggaran 2026",
    clientName: "Pejabat Pengadaan Pada Dinas Perikanan Kota Semarang",
    clientAddress: "Dinas Perikanan Kota Semarang, Semarang",
    location: "Kota Semarang",
    procurementCategory: "Konsultansi IT",
    scopeOfWork: "Pekerjaan Kaji Terap Rekam Kualitas Air Budidaya Ikan Pada Balai Benih Ikan Dinas Perikanan Kota Semarang Tahun Anggaran 2026",
    targetStartDate: "2026-02-24",
    targetEndDate: "2026-06-24",
    documentNumber: "01 / SP / DP / II / 2026",
    documentDate: "2026-02-24",
    procurementRefNo: "PL01A/02/PP-Perikanan/2026",
    executionDays: 120,
    validityDays: 120,
    assignments: [
      {
        id: "assign-ezra-1",
        personId: "person-2",
        proposedPosition: "Water Quality Sensor Specialist",
        roleDescription: "Bertanggung jawab atas integrasi sensor rekam kualitas air budidaya.",
        allocationPercent: 100,
        manMonths: 4,
        billingRateIDR: 17500000,
      },
    ],
    selectedExperienceIds: ["exp-ezra-1"],
    financials: {
      items: [
        {
          id: "fin-ezra-1",
          category: "Personnel",
          description: "Tenaga Ahli E-Government & Sensor Water Quality Specialist",
          quantity: 1,
          unit: "OB",
          durationMonths: 4,
          billingRateIDR: 17500000,
          subtotalIDR: 70000000,
        },
        {
          id: "fin-ezra-2",
          category: "Non-Personnel",
          description: "Sensor Rekam Kualitas Air Budidaya & Multi-Parameter Probe",
          quantity: 1,
          unit: "Paket",
          durationMonths: 1,
          billingRateIDR: 19541580,
          subtotalIDR: 19541580,
        },
      ],
      personnelCostSubtotalIDR: 70000000,
      nonPersonnelCostSubtotalIDR: 19541580,
      directCostSubtotalIDR: 89541580,
      ppnPercent: 11,
      ppnAmountIDR: 9849374,
      grandTotalIDR: 99390954,
      terbilangIDR: "Sembilan Puluh Sembilan Juta Tiga Ratus Sembilan Puluh Ribu Sembilan Ratus Lima Puluh Empat Rupiah",
    },
    status: "Approved",
  },
  {
    id: "proj-sbp-1",
    companyId: "sbp",
    projectName: "Pengembangan Aplikasi Sistem Informasi Data Terpadu Kesejahteraan Sosial (SIDAKSOS) Tahun Anggaran 2023",
    clientName: "Pejabat Pengadaan Barang / Jasa Dinas Sosial Kota Semarang",
    clientAddress: "Dinas Sosial Kota Semarang, Semarang",
    location: "Kota Semarang",
    procurementCategory: "Konsultansi IT",
    scopeOfWork: "Pengembangan Aplikasi Sistem Informasi Data Terpadu Kesejahteraan Sosial (SIDAKSOS) Tahun Anggaran 2023",
    targetStartDate: "2023-05-25",
    targetEndDate: "2023-08-23",
    documentNumber: "01 / DINSOS / SIDAKSOS / V / 2023",
    documentDate: "2023-05-25",
    procurementRefNo: "PL-SIDAKSOS-2023",
    executionDays: 90,
    validityDays: 30,
    assignments: [
      {
        id: "assign-sbp-1",
        personId: "person-1",
        proposedPosition: "Lead Application Developer",
        roleDescription: "Bertanggung jawab atas pengembangan aplikasi SIDAKSOS.",
        allocationPercent: 100,
        manMonths: 3,
        billingRateIDR: 20000000,
      },
    ],
    selectedExperienceIds: [],
    financials: {
      items: [
        {
          id: "fin-sbp-1",
          category: "Personnel",
          description: "Tenaga Ahli System Analyst & Lead Developer",
          quantity: 1,
          unit: "OB",
          durationMonths: 3,
          billingRateIDR: 20000000,
          subtotalIDR: 60000000,
        },
        {
          id: "fin-sbp-2",
          category: "Non-Personnel",
          description: "Sewa Server & Cloud Testing Environment",
          quantity: 1,
          unit: "Paket",
          durationMonths: 1,
          billingRateIDR: 15000000,
          subtotalIDR: 15000000,
        },
      ],
      personnelCostSubtotalIDR: 60000000,
      nonPersonnelCostSubtotalIDR: 15000000,
      directCostSubtotalIDR: 75000000,
      ppnPercent: 11,
      ppnAmountIDR: 8250000,
      grandTotalIDR: 83250000,
      terbilangIDR: "Delapan Puluh Tiga Juta Dua Ratus Lima Puluh Ribu Rupiah",
    },
    status: "Approved",
  },
];

export const MOCK_CONFLICTS: ConflictAlert[] = [
  {
    id: "conf-1",
    severity: "CRITICAL",
    entityName: "Direktur Signatory CV ALFA OMEGA SOLUSINDO",
    field: "Director Name & Deed Match",
    message: "Terdapat perbedaan gelar akademik pada nama Direktur di Akta Pendirian (Ir. Agus Wahyudi) vs Form Legalitas Sistem (Agus Wahyudi, S.T.).",
    sourceA: "Akta Pendirian No. 12 Notaris Hendra S.H. (2018)",
    sourceB: "Profile Form Import NIB OSS (2019)",
    status: "UNRESOLVED",
  },
  {
    id: "conf-2",
    severity: "HIGH",
    entityName: "Compliance Evidence BPE",
    field: "Monthly BPE August 2026",
    message: "BPE Bulan Agustus 2026 belum diunggah atau belum terkonfirmasi oleh KPP Pratama. Dokumen prakualifikasi membutuhkan bukti bayar pajak 3 bulan terakhir.",
    sourceA: "Compliance Tax Repository Checklist",
    sourceB: "Syarat Prakualifikasi Pengadaan DKP 2026",
    status: "UNRESOLVED",
  },
];
